name: Create Archives
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get git repo
        uses: actions/checkout@v1
      - name: Create folders
        run: |
          mkdir -p build
          mkdir -p builds
      - name: Zip files
        run: |
          declare -a rps=( default light oled )
          for rp in "${rps[@]}"
          do
            changes=$(git log --since="yesterday" --patch HEAD "$rp"/)
            if [ -n "$changes" ]; then
                cd $rp
                zip -r ../build/"$rp".zip *
                cd ../
               mv -u ./build/"$rp".zip ./builds/"$rp".zip
            fi
          done
      - name: Delete temp folder
        run: rm -R build
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          changes=$(git status -s)
          echo -e $changes
          if [ ! -z "$changes" ]; then
            git commit -m "Automated build" -a
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
