name: Create Archives
on: 
  push:
    paths:
      - '!builds/**'
      - '*/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get git repo
        uses: actions/checkout@v1
      - name: Create folders
        run: |
             mkdir -p build 
             mkdir -p builds
      - name: Zip files
        run: |
             if [ ! -z "$(git diff --numstat HEAD~1 HEAD default/)" ] || [ ! -f "./build/default.zip" ]; then
                zip -q -r ./build/default.zip ./default/*
                mv -u ./build/default.zip ./builds/default.zip
             fi
             if [ ! -z "$(git diff --numstat HEAD~1 HEAD light/)" ] || [ ! -f "./build/light.zip" ]; then
               zip -q -r ./build/light.zip ./light/*
               mv -u ./build/light.zip ./builds/light.zip
             fi
             if [ ! -z "$(git diff --numstat HEAD~1 HEAD oled/)" ] || [ ! -f "./build/oled.zip" ]; then
               zip -q -r ./build/oled.zip ./oled/*
               mv -u ./build/oled.zip ./builds/oled.zip
             fi
      - name: Delete temp folder
        run: rm -R build
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          changes=$(git status -s)
          echo -e $changes
          if [ ! -z "$changes" ]; then
            git commit -m "Automated build" -a
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
